# Generated by Django 4.0.5 on 2022-07-15 19:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0003_cart_id_alter_cart_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartItems',
            new_name='Items',
        ),
    ]
